export const ADD_SENSOR = 'ADD_SENSOR';
export const UPDATE_SENSOR_LATEST_VALUE = 'UPDATE_SENSOR_LATEST_VALUE';

// View
export const TOGGLE_BLUEPRINT_EDIT_MODE = 'TOGGLE_BLUEPRINT_EDIT_MODE';
export const TOGGLE_VIEW_EDIT_MODE = 'TOGGLE_VIEW_EDIT_MODE';
export const BLUEPRINT_ADD_EXTERIOR_WALL = 'BLUEPRINT_ADD_EXTERIOR_WALL';
export const BLUEPRINT_ADD_INTERIOR_WALL = 'BLUEPRINT_ADD_INTERIOR_WALL';
export const BLUEPRINT_CLEAR_INTERIOR_WALL = 'BLUEPRINT_CLEAR_INTERIOR_WALL';
export const BLUEPRINT_SET_DATA = 'BLUEPRINT_SET_DATA';

export const VIEW_SET_DATA = 'VIEW_SET_DATA';

// Sensors
export const VIEW_SET_SENSOR_POSITION = 'VIEW_SET_SENSOR_POSITION';
export const VIEW_SET_SENSOR_VISIBILITY = 'VIEW_SET_SENSOR_VISIBILITY';
export const VIEW_SET_SENSOR_DATA = 'VIEW_SET_SENSOR_DATA';

// Journal
export const TOGGLE_JOURNAL_ADD_MODE = 'TOGGLE_JOURNAL_ADD_MODE';
export const JOURNAL_SET_MESSAGES = 'JOURNAL_SET_MESSAGES';
