export const ADD_SENSOR = 'ADD_SENSOR';
export const UPDATE_SENSOR_LATEST_VALUE = 'UPDATE_SENSOR_LATEST_VALUE';

// Blueprint
export const TOGGLE_BLUEPRINT_EDIT_MODE = 'TOGGLE_BLUEPRINT_EDIT_MODE';
export const BLUEPRINT_ADD_EXTERIOR_WALL = 'BLUEPRINT_ADD_EXTERIOR_WALL';
export const BLUEPRINT_ADD_INTERIOR_WALL = 'BLUEPRINT_ADD_INTERIOR_WALL';
export const BLUEPRINT_CLEAR_INTERIOR_WALL = 'BLUEPRINT_CLEAR_INTERIOR_WALL';
export const BLUEPRINT_SET_DATA = 'BLUEPRINT_SET_DATA';

// Journal
export const TOGGLE_JOURNAL_ADD_MODE = 'TOGGLE_JOURNAL_ADD_MODE';
export const JOURNAL_SET_MESSAGES = 'JOURNAL_SET_MESSAGES';
